name: Deploy Pomodoro Timer to GitHub Pages

on:
  push:
    branches:
      - main   

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload website files
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            index.html
            app.js
            assets/
            images/
            css/
            js/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
